import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as scripts from './inline-scripts.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const hash = (s) => `sha256-${createHash('sha256').update(s, 'utf8').digest('base64')}`;
const entries = Object.entries(scripts);
const out = `// Generated by scripts/build-inline.mjs. Do not edit; edit scripts/inline-scripts.mjs.
export interface HWioInlineScript { code: string; hash: string }
${entries.map(([k, v]) => `export const ${k}: HWioInlineScript = ${JSON.stringify({ code: v, hash: hash(v) })};${/hw_/.test(v) ? ' // legacy-ok: reads the pre-design-system storage keys once' : ''}`).join('\n')}
export const hwioInlineHashes: string[] = [${entries.map(([k]) => `${k}.hash`).join(', ')}];
`;
writeFileSync(join(here, '../src/inline.ts'), out);
console.log(`inline: ${entries.length} bootstrap scripts hashed`);
